[project]
name = "script_orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.15"
dependencies = [
    "dagster",
    "dagster-cloud",
    "python-dotenv",
    "pyyaml",
    "gitpython",
    "pydantic",
    "pyspark>=4.1.1",
    "dask[distributed]>=2026.1.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
    "dagster-dask>=0.28.14",
    "prefect>=3.0.0",
    "requests",
    "beautifulsoup4",
    "dagster-webserver>=1.12.14",
    "dagster-dg-cli>=1.12.14",
    "griffe>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver",
    "pytest",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "script_orchestrator"

[tool.setuptools.packages.find]
exclude=["script_orchestrator_tests"]

[dependency-groups]
dev = [
    "dagster-webserver>=1.12.14",
]
