"""
DAG Factory Example - Customer ETL Pipeline

This demonstrates the DAG Factory pattern where multiple similar DAGs
are parameterized by customer_id. In Dagster, this maps to a partitioned asset.

Traditional Airflow DAG Factory pattern:
  - customer_a_etl_dag
  - customer_b_etl_dag
  - customer_c_etl_dag

Dagster Equivalent:
  - Single partitioned asset with partitions: ["customer_a", "customer_b", "customer_c"]
"""
from datetime import datetime
from airflow.decorators import dag, task


# This would normally be generated by DAG Factory from a config file
# In Dagster, we convert this to a partitioned asset
@dag(
    dag_id="customer_etl_template",
    start_date=datetime(2024, 1, 1),
    schedule="@daily",
    catchup=False,
    tags=["dag_factory", "customer_etl"],
    params={
        "customer_id": "template",  # Will be replaced with actual customer_id
    }
)
def customer_etl_pipeline():
    """
    Template DAG for customer ETL.
    DAG Factory would generate multiple instances with different customer_ids.
    Dagster converts this to a single partitioned asset.
    """

    @task
    def extract_customer_data(**context):
        """Extract data for specific customer."""
        customer_id = context["params"]["customer_id"]
        print(f"Extracting data for customer: {customer_id}")
        return {"customer_id": customer_id, "records": 1000}

    @task
    def transform_customer_data(data):
        """Transform customer data."""
        print(f"Transforming data for customer: {data['customer_id']}")
        data["transformed"] = True
        return data

    @task
    def load_customer_data(data):
        """Load customer data to warehouse."""
        print(f"Loading data for customer: {data['customer_id']}")
        print(f"Loaded {data['records']} records")
        return {"status": "success"}

    # Pipeline flow
    extracted = extract_customer_data()
    transformed = transform_customer_data(extracted)
    load_customer_data(transformed)


# Instantiate the template DAG
customer_etl_dag = customer_etl_pipeline()


# In traditional DAG Factory, you'd have a loop that creates multiple DAGs:
# for customer_id in ["customer_a", "customer_b", "customer_c"]:
#     dag_id = f"customer_{customer_id}_etl"
#     # Create DAG with customer_id parameter
#     globals()[dag_id] = create_dag(customer_id)

# In Dagster with our component, the dag_factory config automatically
# converts this to a partitioned asset with partitions for each customer!
